INSERT INTO [dbo].[StudentApplications]
           ([StudentID]
           ,[Motivation]
           ,[BursaryAmount]
           ,[StatusID]
           ,[Reviewer_UserID]
           ,[ReviewerComment]
           ,[Date]
           ,[UniversityStaffID]
           ,[BursaryDetailsID])
     VALUES

(1,'I am writing to support this bursary application for a student who has consistently shown dedication to their studies and community.',125000,3,3,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-01',22,1),
(2,'The student applying for this bursary has demonstrated outstanding academic achievements and a strong commitment to their education.',75000,4,4,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-11-04',16,1),
(3,'I believe this student is a deserving candidate for the bursary due to their perseverance and passion for learning.',40000,3,5,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-05',16,1),
(4,'The applicant has not only excelled academically but has also actively contributed to the school community through various extracurricular activities.',40000,3,6,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-06',31,1),
(6,'I am confident that this student will make the most of the bursary opportunity to further their education and reach their full potential.',30000,3,7,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-07',13,1),
(7,'Having taught the applicant, I can attest to their determination and drive to succeed despite facing challenges.',75000,3,8,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-08',16,1),
(8,'This student''s dedication to their education and their desire to make a difference make them an excellent candidate for the bursary.',40000,4,9,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-11-11',22,1),
(9,'The applicant has consistently demonstrated leadership qualities and a strong sense of responsibility both in and out of the classroom.',40000,4,10,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-11-12',16,1),
(11,'I fully endorse this student''s application for the bursary based on their academic performance and their commitment to personal growth.',45000,4,3,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-11-13',13,1),
(12,'The student applying for this bursary has shown resilience and a positive attitude towards their studies despite difficult circumstances.',75000,4,4,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-11-14',37,1),
(13,'I believe the bursary would greatly benefit this student, who has shown exceptional promise and dedication to their education.',50000,4,5,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-11-15',22,1),
(14,'The applicant has a clear vision for their future and demonstrates the determination to overcome any obstacles in their path.',40000,4,6,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-11-18',31,1),
(16,'This student''s passion for learning and their desire to succeed make them a strong candidate for the bursary.',40000,3,7,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-19',16,1),
(18,'The applicant has a demonstrated track record of academic excellence and a genuine enthusiasm for their chosen field of study.',45000,3,8,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-20',37,1),
(19,'I am impressed by this student''s initiative and proactive approach to their education, which make them a deserving candidate for the bursary.',75000,3,9,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-21',31,1),
(20,'The student applying for this bursary has displayed a commendable level of maturity and responsibility in their academic pursuits.',75000,3,10,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-22',22,1),
(21,'I believe this student''s dedication to their studies and their commitment to personal development make them a strong contender for the bursary.',40000,3,3,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-25',16,1),
(23,'This student has shown remarkable progress and growth during their time at our school, making them a deserving recipient of the bursary.',30000,3,4,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-25',31,1),
(24,'I am confident that this student will make the most of the bursary opportunity and use it to further their academic and career goals.',40000,4,5,'Unfortunately, your bursary application was unsuccessful as it did not meet the minimum grade requirements. We appreciate your interest in the program, but we are unable to proceed with your application based on the set criteria. We encourage you to continue working towards your academic goals.','2019-11-26',31,1),
(26,'The applicant has a demonstrated track record of academic excellence and a genuine enthusiasm for their chosen field of study.',50000,4,5,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-11-26',37,1),
(27,'The applicant''s academic achievements and extracurricular involvement demonstrate their well-roundedness and readiness for higher education.',75000,4,6,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-11-26',16,1),
(28,'I believe the bursary would provide invaluable support to this student, who has shown exceptional potential and determination to succeed.',30000,3,7,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-26',37,1),
(29,'This student''s commitment to their education and their desire to give back to their community make them an ideal candidate for the bursary.',40000,3,8,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-27',31,1),
(31,'The applicant''s perseverance and dedication to their studies make them a deserving candidate for the bursary.',30000,4,9,'Unfortunately, your bursary application was unsuccessful as it did not meet the minimum grade requirements. We appreciate your interest in the program, but we are unable to proceed with your application based on the set criteria. We encourage you to continue working towards your academic goals.','2019-11-28',16,1),
(32,'I have been consistently impressed by this student''s work ethic and determination to succeed, making them a strong contender for the bursary.',40000,3,10,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-11-28',16,1),
(34,'This student''s positive attitude and willingness to go above and beyond in their academic pursuits make them a deserving recipient of the bursary.',25000,4,3,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-11-28',37,1),
(35,'The applicant''s academic achievements and involvement in extracurricular activities demonstrate their commitment to personal and academic growth.',25000,4,4,'We regret to inform you that your bursary application was unsuccessful because the amount requested exceeds the bursary funds allocated for this cycle. Unfortunately, we are unable to accommodate applications that surpass our allotted budget. We encourage you to explore other funding options and wish you success in your endeavors.','2019-12-02',13,1),
(36,'I believe this student has the potential to excel academically and make a positive impact in their chosen field, with the support of the bursary.',25000,4,5,'We regret to inform you that your bursary application was unsuccessful because the amount requested exceeds the bursary funds allocated for this cycle. Unfortunately, we are unable to accommodate applications that surpass our allotted budget. We encourage you to explore other funding options and wish you success in your endeavors.','2019-12-02',31,1),
(37,'This student''s dedication to their studies and their eagerness to learn make them a deserving candidate for the bursary.',75000,4,6,'We regret to inform you that your bursary application was unsuccessful because the amount requested exceeds the bursary funds allocated for this cycle. Unfortunately, we are unable to accommodate applications that surpass our allotted budget. We encourage you to explore other funding options and wish you success in your endeavors.','2019-12-04',16,1),
(37,'I am impressed by this student''s determination and resilience in the face of challenges, which make them a strong contender for the bursary.',50000,3,7,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-05',16,1),
(38,'The applicant has shown great initiative and resourcefulness in pursuing their academic goals, making them a deserving recipient of the bursary.',75000,4,8,'We regret to inform you that your bursary application was unsuccessful because the amount requested exceeds the bursary funds allocated for this cycle. Unfortunately, we are unable to accommodate applications that surpass our allotted budget. We encourage you to explore other funding options and wish you success in your endeavors.','2019-12-05',22,1),
(39,'This student''s passion for their chosen field of study and their commitment to personal growth make them a strong candidate for the bursary.',100000,3,9,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-05',37,1),
(40,'The applicant''s exemplary academic record and involvement in extracurricular activities highlight their dedication and readiness for higher education, making them an excellent candidate for the bursary.',100000,3,10,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-05',37,1),
(41,'I believe this student''s enthusiasm for learning and their proactive approach to their education make them a deserving recipient of the bursary.',40000,4,3,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-12-05',16,1),
(42,'The applicant has consistently demonstrated a strong commitment to their studies and has shown great potential for future success, making them an ideal candidate for the bursary.',40000,4,4,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-12-06',31,1),
(43,'This student''s perseverance and resilience in overcoming obstacles demonstrate their determination to succeed, making them a deserving candidate for the bursary.',40000,4,5,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-12-06',31,1),
(44,'I am confident that this student will make the most of the bursary opportunity to further their academic and career aspirations, based on their demonstrated commitment to personal and academic growth.',100000,3,6,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-06',31,1),
(45,'The applicant''s dedication to their studies and their involvement in community service reflect their strong values and sense of responsibility, making them a worthy recipient of the bursary.',100000,4,7,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-12-09',31,1),
(46,'I believe this student''s academic achievements and their commitment to serving others make them an excellent candidate for the bursary.',25000,3,8,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-09',13,1),
(47,'The applicant''s passion for learning and their eagerness to explore new opportunities demonstrate their readiness for higher education, making them a deserving candidate for the bursary.',125000,4,9,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-12-09',31,1),
(48,'This student''s positive attitude and determination to succeed make them a strong contender for the bursary, as they have consistently shown a willingness to go above and beyond in their academic pursuits.',125000,3,10,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-10',31,1),
(49,'I am impressed by this student''s dedication to their studies and their proactive approach to their education, which make them a deserving recipient of the bursary.',125000,4,3,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-12-10',31,1),
(50,'The applicant''s academic achievements and their involvement in extracurricular activities demonstrate their well-roundedness and readiness for the challenges of higher education, making them a strong candidate for the bursary.',125000,4,4,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-12-11',22,1),
(51,'I believe this student''s commitment to their education and their desire to make a difference in their community make them an excellent candidate for the bursary.',125000,3,5,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-12',22,1),
(52,'The applicant''s perseverance and determination to overcome obstacles highlight their resilience and readiness for the opportunities that the bursary would provide.',125000,4,6,'We regret to inform you that your bursary application was unsuccessful due to age requirements. Unfortunately, you did not meet the specified age criteria for eligibility. We encourage you to explore other opportunities and wish you the best in your future endeavors.','2019-12-12',22,1),
(53,'This student''s academic achievements and their passion for learning make them a deserving recipient of the bursary, as they have consistently demonstrated a dedication to their studies.',65000,3,7,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-12',13,1),
(54,'I am confident that this student will make a positive impact in their chosen field of study, with the support of the bursary, based on their demonstrated potential and commitment to personal growth.',65000,3,8,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-12',13,1),
(55,'The applicant''s strong work ethic and their willingness to take on challenges demonstrate their readiness for higher education, making them a worthy recipient of the bursary.',70000,3,9,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-13',13,1),
(79,'I believe this student''s dedication to their studies and their desire to succeed against all odds make them a deserving candidate for the bursary.',100000,3,10,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-13',22,1),
(80,'The applicant''s academic achievements and their involvement in extracurricular activities highlight their leadership qualities and their commitment to personal development, making them an ideal candidate for the bursary.',100000,3,3,'Congratulations! Your bursary application has been approved. We were impressed by your qualifications and achievements, and we believe that this bursary will help you achieve your educational goals. We look forward to supporting you in your academic journey.','2019-12-13',13,1);
