INSERT INTO Universities (UniversityName, IsActiveRecipient)
VALUES 
('University of Cape Town', 1),
('University of the Witwatersrand', 1),
('Stellenbosch University', 1),
('University of Pretoria', 1),
('University of Johannesburg', 0),
('University of KwaZulu-Natal', 1),
('University of the Western Cape', 0),
('Rhodes University', 1),
('Nelson Mandela University', 1),
('University of Limpopo', 0),
('University of Venda', 1),
('University of Fort Hare', 0),
('University of Zululand', 1),
('University of Mpumalanga', 1),
('Tshwane University of Technology', 1),
('Cape Peninsula University of Technology', 1),
('Durban University of Technology', 0),
('Central University of Technology', 1),
('Mangosuthu University of Technology', 1),
('Vaal University of Technology', 0),
('Walter Sisulu University', 1),
('North-West University', 1),
('University of Free State', 1),
('Sefako Makgatho Health Sciences University',0),
('Sol Plaatje University', 1),
('University of South Africa', 1),
('South African College of Music', 0),
('Regenesys Business School', 0),
('Pearson Institute of Higher Education', 0),
('African Leadership Academy', 0),
('African School of Economics', 0),
('AFDA, The School for the Creative Economy', 0),
('Aros', 0);
